version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  product-pg:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-product}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-product}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/entrypoints/product:/docker-entrypoint-initdb.d

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug

volumes:
  pgdata: